server:
  port: 8080

spring:
  application:
    name: filmparser
  profiles:
    active: dev #SPRING_PROFILES_ACTIVE

parser:
  movieCount: ${MOVIE_COUNT:1000}
  startPage: ${START_PAGE:1}
  base-url: https://www.kinopoisk.ru
  films-url: /lists/movies/?b=films
  page-size: 50
  timeout:
    ms: 10000
  max-retries: 5
  selectors:
    movie: ".styles_root__ti07r"
    title: ".styles_mainTitle__IFQyZ"
    original-title: ".desktop-list-main-info_secondaryTitle__ighTt"
    rating: ".styles_kinopoiskValue__nkZEC"
    url: ".base-movie-main-info_link__YwtP1"
    meta: ".desktop-list-main-info_truncatedText__IMQRP"
    year: ".desktop-list-main-info_secondaryText__M_aus"
    not-found: ".styles_heading__F1VCE"
