server:
  port: 8080

spring:
  application:
    name: filmparser
  profiles:
    active: dev #SPRING_PROFILES_ACTIVE

parser:
  movieCount: ${MOVIE_COUNT:1000}
  base-url: https://www.kinopoisk.ru
  films-url: /lists/movies/?b=films
  page-size: 50
  timeout:
    ms: 5000
  max-retries: 10
  selectors:
    movie: ".styles_root__ti07r"
    title: ".styles_mainTitle__IFQyZ"
    original-title: ".desktop-list-main-info_secondaryTitle__ighTt"
    rating: ".styles_kinopoiskValue__nkZEC"
    url: ".base-movie-main-info_link__YwtP1"
    meta: ".desktop-list-main-info_truncatedText__IMQRP"
    year: ".desktop-list-main-info_secondaryText__M_aus"
  user-agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.94 Safari/537.36"
    - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
    - "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edg/124.0.2478.67"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.100 Safari/537.36"

